### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by LolHens**
I put together a Dockerfile for this project. Maybe you even want to make a separate repository for this.
For a working example see:
https://cloud.docker.com/repository/docker/lolhens/polynote
https://github.com/LolHens/docker-polynote

### CODE REVIEW

**Comment by jeremyrsmith** [comment]
Welcome! Thanks for the PR! It will be great to have a Docker distribution.

Maybe the dockerfile could have some networking configuration and some configuration tweaks? @jeremyalan mentioned on #528 that because by default Polynote listens on 127.0.0.1 only, it can't be accessed when inside of docker. We definitely don't want it listening on public interfaces by default (since it can execute arbitrary code); can Docker forward localhost:8192 on the host to localhost:8192 in the container?

I'm no docker expert, so help is definitely appreciated here!

**Comment by jeremyalan** [comment]
X-post from #528 - I was able to get this working, which wasn't too bad:
```
docker run --rm -p 8192:8192 -e "POLYNOTE_CONFIG=listen:\n  host: 0.0.0.0" lolhens/polynote
```

This provides an opt-in / "buyer beware" configuration, to open up all public interfaces when it makes sense for the deployment.  In this case, having it running inside a Docker container on my workstation doesn't seem too risky.

**Comment by dmvieira** [comment]
Do you think about spark support in this PR?

**Comment by LolHens** [comment]
> 
> 
> Do you think about spark support in this PR?

I think it would probably be preferable to have two seperate images. One without and one with spark.
I already made an image with spark included but it probably needs some more testing: https://cloud.docker.com/repository/docker/lolhens/polynote-spark

If dockerhub is the preferred build tool for the images then the two Dockerfiles would also have to live in separate repositories.

**Comment by dmvieira** [comment]
Great! If you need some help with spark I will be glad to help!

**Comment by mathematicalmichael** [comment]
> X-post from #528 - I was able to get this working, which wasn't too bad:
> 
> ```
> docker run -p 8192:8192 -e "POLYNOTE_CONFIG=listen:\n  host: 0.0.0.0" lolhens/polynote
> ```
> 
> This provides an opt-in / "buyer beware" configuration, to open up all public interfaces when it makes sense for the deployment. In this case, having it running inside a Docker container on my workstation doesn't seem too risky.

This `docker run` did not work for me. It completed and ran, but I couldn't access it via web browser.

**Comment by JD557** [comment]
@mathematicalmichael I also had problems with the newlines. Using YAML's inline syntax also works:

`docker run -p 8192:8192 -e "POLYNOTE_CONFIG=listen: { host: 0.0.0.0 }" lolhens/polynote`

**Comment by mathematicalmichael** [comment]
@jonathanindig just a heads up as feedback for the docker image from @LolHens:
I was finally able to get it running but none of the python packages that were being installed from the instructions in the top notebook cell were accessible in the cells below. fiddled for an hour or so but couldn't get it to work, so, something with the linkage of python paths was off I think.

**Comment by jonathanindig** [comment]
@mathematicalmichael Do you have the same problem with the official docker images?

**Comment by mathematicalmichael** [comment]
@jonathanindig actually I can't seem to access the container's ports at all. I followed the instructions in the docker folder to a tee and tried two different versions of images. I'm not a novice with Docker, either, so I'm actually pretty surprised this has been as difficult as it's proving to be.

I see it start up and run, and have tried omitting the binding to `127.0.0.1` with no success. tried chrome and safari, `localhost` and `127.0.0.1` and all permutations thereof. The `latest` tag shows "localhost didn't send any data", and the `0.2.12-2.12` tag didn't connect at all. 


I am seeing the container printout show "Server running at 127.0.0.1" which makes me suspect the `config.yaml` is being ignored, despite seeing "Loading configuration from /opt/config/config.yaml"
print out. 

(2019 Macbook Pro)

**Comment by jonathanindig** [comment]
Definitely sounds like the config isn't being read properly based on that log. 

Here's what my environment looks like when I run it using the command in the instructions:
```
$ pwd
/Users/jindig/projects/polynote-docker
```
```
$ tree                        
.
├── config.yml
└── notebooks
    └── my\ first\ notebook.ipynb

1 directory, 2 files
```

```
$ cat config.yml                                                                                                                                                   Thu Nov  7 12:40:40 2019
listen:
  host: 0.0.0.0
```

Does yours look similar? It might be easier to debug this further [on gitter](https://gitter.im/polynote/polynote), come join us! 😄

**Comment by mathematicalmichael** [comment]
````
mmbp:polynote-docker michael.pilosov$ pwd
/Users/michael.pilosov/repos/polynote-docker
mmbp:polynote-docker michael.pilosov$ tree
.
├── config.yml
└── notebooks

1 directory, 1 file
mmbp:polynote-docker michael.pilosov$ cat config.yml
listen:
  host: 0.0.0.0
mmbp:polynote-docker michael.pilosov$
```

I deleted and re-created the config file. I wonder if it's because I called it `.yaml`?
Anyway, thank you for your help. Guess it just took another retry. It works, I'm not encountering the Python linking bugs I was before. I'm able to install numpy/scipy and access them in cells below. Excellent. 

I did accidentally put the packages in the wrong part of the cell, though, so I may suggest making it a bit clearer that it's the top third that needs the packages and not the middle ("resolvers"). 

But anyway, thank you so much for your help! I'm excited to play around with this more (especially trying out porting existing notebooks) once I find some time. Your docker image was exactly what I needed, might I suggest highlighting it on the homepage README? ;D

**Comment by jonathanindig** [comment]
Happy to help! Feel free to submit a PR with your suggested edit to the readme 😉

**Pull request closed without merging**
