### PR TITLE
Add option to run this cell and all the cells below

### PR DESCRIPTION
**Pull request by omidmogasemi**
Addresses #1283. Note that the right image now means "run this cell and all cells below" instead of "run all cells above and this cell". I was rather limited on free images from FontAwesome...

image

### CODE REVIEW

**Comment by jeremyrsmith** [comment]
I don't really want to change the meaning of the icon (and besides, I think the "▶︎▶︎|" icon visually represents "run all from the beginning and then stop here" pretty well).
continue

Try this one for the new button (run this and then all following) and see how it looks. I hacked it together from the existing ones.

**Comment by omidmogasemi** [comment]
Thanks! I think this makes more sense 

image

**Comment by jeremyrsmith** [comment]
> Thanks! I think this makes more sense
> 
> image

Oof, It looks pretty bad when it's all shrunk down. But we can fiddle with it some more later.

**Review by jeremyrsmith — APPROVED** [review]

**Comment by jeremyrsmith** [comment]
This will probably want a hotkey, but we can do that separately when it comes up.

**Comment by omidmogasemi** [comment]
Ah I completely forgot - I'll add that in when doing custom hotkey configuration soon.

**Comment by jonathanindig** [comment]
Could you update the docs too? 😬 Thanks!

**Comment by omidmogasemi** [comment]
Yes! Working on that now - unfortunately my last few PRs outdated quite a few areas so I'm bundling it into a larger PR. 

Next time I'll definitely bundle documentation updates together :)

**Comment by jonathanindig** [comment]
Honestly, if you know you're going to be making a lot of changes it's not a bad idea to batch the documentation updates. Otherwise you might end up taking the same screenshot again and again... 

So, your approach is totally fine! As long as the docs get updated before we release :)

**Pull request merged**
