### PR TITLE
Better handling of remote kernel errors

### PR DESCRIPTION
**Pull request by jeremyrsmith**
Currently if any remote kernel operation (other than `queueCell`) results in an error, it isn't handled and can result in the death of the remote kernel process.

Instead, catch those errors and propagate them to the server, where they already do get handled.

This should solve some common "broken pipe" errors (e.g. #597), though it doesn't have any handling for if the network connection actually does die. That should be pretty rare (at least if the kernel is just a subprocess talking over the loopback interface) but we should add some recovery mechanism in the future.

### CODE REVIEW

**Comment by ildarlomov** [comment]
I still face the issue from  #597. Has it been resolved in the latest version of docker image?

**Comment by ildarlomov** [comment]
[ERROR] Fiber failed.
        A checked error was not handled.
        java.io.IOException: Broken pipe
        	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        	at polynote.kernel.remote.SocketTransport$FramedSocket$$anonfun$write$1.apply$mcV$sp(transport.scala:383)
        	at polynote.kernel.remote.SocketTransport$FramedSocket$$anonfun$write$1.apply(transport.scala:375)
        	at polynote.kernel.remote.SocketTransport$FramedSocket$$anonfun$write$1.apply(transport.scala:375)
        	at zio.blocking.Blocking$Service$$anonfun$effectBlocking$1$$anonfun$apply$3.apply(Blocking.scala:133)
        	at zio.blocking.Blocking$Service$$anonfun$effectBlocking$1$$anonfun$apply$3.apply(Blocking.scala:127)
        	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:333)
        	at zio.internal.FiberContext.zio$internal$FiberContext$$run$body$2(FiberContext.scala:602)
        	at zio.internal.FiberContext$$anonfun$7.run(FiberContext.scala:602)
        	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        	at java.lang.Thread.run(Thread.java:748)

**Comment by jeremyrsmith** [comment]
@ildarlomov does this happen when killing/stopping the kernel? Or does it happen during normal notebook operation?

**Comment by ildarlomov** [comment]
It happens when kernel dies at any reason during execution. In my case this is OOM caused errors, in particular it was  WARN IndexShuffleBlockResolver: Error deleting index /tmp/blockmgr-6c6cb681-54d8-4411-bbf0-4bbb9d9baded/14/shuffle_0_1168_0.index
I've fixed this by adding more memory to the driver for now.  Errors handling seems to be unreliable now, cuz I can't even restart kernels in all died notebooks

**Pull request merged**
