### PR TITLE
Add DEVELOPING.md with dependencies and build steps

### PR DESCRIPTION
**Pull request by easel**
First pass at some documenting build dependencies and steps. Feedback welcome!

### CODE REVIEW

**Comment by JD557** [comment]
Can you also add a reference to the dev docker image: https://github.com/polynote/polynote/tree/master/docker#dev-image ?

It's a bit slower to use that for development, but it helps if for some reason you can't (or don't want to) mess around with your local python/spark setup.

**Comment by easel** [comment]
@JD557 sure thing! Take look and let me know if it works -- I've never used the docker image but it looks like the instructions necessary are in the link you suggested.

**Comment by jeremyrsmith** [comment]
Thanks @easel! This is a great start. Should have merged this ages ago, sorry about that!

**Comment by easel** [comment]
All good, in before the EOY!~ Thanks for the merge and Happy New Year!

**Pull request merged**
