### PR TITLE
refactor NotebookContext into SharedNotebook rather than each individual kernel

### PR DESCRIPTION
**Pull request by indig**
Seems to work! 🤞 😬

### CODE REVIEW

**Comment by jeremyrsmith** [comment]
When the notebook is changed, how does `RemoteSparkKernelClient` get the memo?

**Comment by indig** [comment]
Ok, I think I got it to work but it's kind of an ugly change - basically everywhere now has: ```
notebookContext: SignallingRef[IO, (NotebookContext, Option[NotebookUpdate])]
```

When the NotebookContext is changed based on a NotebookUpdate, that update is saved alongside the context. When the NotebookContext is changed due to another reason, there is no update saved alongside it. 

RemoteSparkKernel listens to the changes to that signal and if there's an update sends it to the remote client. 

Definitely open to making this better! I think two options might be: just add a notebookupdate stream when creating Kernels (😞). Or, potentially change the unit of "remoteness" from Kernel to something new (RemoteNotebook?) which could do the special remote stuff without polluting the general KernelAPI.

**Comment by indig** [comment]
Hmm, not sure why the build failed but RemoteSparkKernelSpec runs fine in my IntelliJ...

**Comment by indig** [comment]
Will need to circle back to this later, no point in keeping it open.

**Pull request closed without merging**
