### PR TITLE
[WIP] add test for pyspark interpreter. check if 'kernel' is present

### PR DESCRIPTION
**Pull request by kervel**
Done to prevent regressions on #706

### CODE REVIEW

**Comment by kervel** [comment]
not yet ok, jep.JepException: <class 'ModuleNotFoundError'>: No module named 'py4j'

**Comment by jonathanindig** [comment]
@kervel Given #743 you should be able to rebase and add your test into https://github.com/polynote/polynote/blob/master/polynote-spark/src/test/scala/polynote/kernel/interpreter/python/PySparkInterpreterSpec.scala

Make sure you call `initialize()` on the new test (I'm planning on refactoring that test later this week as it's quite hacky as it is)

**Comment by kervel** [comment]
ok like this ?

**Comment by jonathanindig** [comment]
Looks great, thanks!

**Pull request merged**
