### PR TITLE
py4j gateway not secure using PySpark 2.4.4 

### PR DESCRIPTION
**Pull request by ghoto**
I tested this with Spark 2.4.4 and there is no need to set `PYSPARK_ALLOW_INSECURE_GATEWAY=1`.

GatewayServer is created with a GatewayServerBuilder which allows setting an auth_token, this token is a random alphanumeric string length 256, it's initialized the first time the gateway is created.

Note that the version of py4j in polynote-kernel was too old.

This is the issue https://github.com/polynote/polynote/issues/602

### CODE REVIEW

**Comment by ghoto** [comment]
Tested on 2.4.4 and 2.3.1

**Comment by jeremyrsmith** [comment]
Hmmm, so the issue with this is that if we want to support Spark 2.1, we can't directly depend on that newer Py4J version as it won't be what's deployed by Spark.

**Comment by jeremyrsmith** [comment]
Let's plan to deprecate Spark 2.1 soon, and we'll keep this PR open for when we do that.

**Comment by madhusudhannr** [comment]
Same issue is there with Jupyter notebook with Spark245, even after setting env variable 
PYSPARK_ALLOW_INSECURE_GATEWAY=1

**Pull request merged**
