### PR TITLE
SQLContext._get_or_create instead of deprecated _wrapped

### PR DESCRIPTION
**Pull request by jbguerraz**
Since https://github.com/apache/spark/commit/88696ebcb72fd3057b1546831f653b29b7e0abb2 (https://issues.apache.org/jira/browse/SPARK-38121) Polynote won't works because `sqlContext = spark._wrapped` rely on deprecated `_wrapped`, we now have to use `SQLContext._get_or_create()`
This  has been tested with spark 3.3.1.

### CODE REVIEW

**Comment by jeremyrsmith** [comment]
@jbguerraz Does this change break Spark 2.4? I.e. is it backwards-compatible?

**Comment by jbguerraz** [comment]
> @jbguerraz Does this change break Spark 2.4? I.e. is it backwards-compatible?

looks like not since this `_get_or_create` appeared here https://github.com/apache/spark/commit/88696ebcb72fd3057b1546831f653b29b7e0abb2

gonna patch it now!

**Comment by jeremyrsmith** [comment]
@jbguerraz if you rebase onto master, it should solve the build error

**Comment by jbguerraz** [comment]
Thank you @jeremyrsmith 
Looks like checks passed now :)

**Comment by jbguerraz** [comment]
any chance to take another look @jeremyrsmith ? thank you a lot!

**Review by jonathanindig — APPROVED** [review]

**Comment by jonathanindig** [comment]
Thanks @jbguerraz ! Sorry for the delay in reviewing!

**Pull request merged**
