### PR TITLE
Draft: Upgrade jep to v4.0.x

### PR DESCRIPTION
**Pull request by austinkeller**

### CODE REVIEW

**Comment by jonathanindig** [comment]
Hi @austinkeller thanks for the contribution! 

Were you able to confirm that this is all that is needed to upgrade jep to 4.0? I think at least the version on the Scala side would likely need to be updated as well :)

**Comment by austinkeller** [comment]
ah no, I was hoping that creating the MR would run tests though, since I was having trouble building locally.

**Comment by austinkeller** [comment]
updated the MR title for clarity

**Comment by austinkeller** [comment]
I'm maintaining the AUR package for polynote and wanted to get a feel for whether jep 4 might be supported soon, or whether I should create a new jep 3 AUR package

**Comment by jonathanindig** [comment]
Sorry, what is an AUR package?

**Comment by austinkeller** [comment]
oh, sorry. AUR is the [Arch User Repository](https://wiki.archlinux.org/title/Arch_User_Repository), one of the package repos for Arch Linux

**Comment by austinkeller** [comment]
Here's the package https://aur.archlinux.org/packages/polynote/

This lets users on an arch-based distro install polynote and all of it's dependencies with `pacman -S polynote`

**Comment by jonathanindig** [comment]
Hi @austinkeller, just released 0.4.4 which includes #1222 which upgrades Jep to 4.0.0. I'll close this PR now, thanks!

**Comment by austinkeller** [comment]
Updated the package and it's working with python-jep 4.0.0, thanks!

**Pull request closed without merging**
